// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Earth: typeof import('./src/components/Earth.vue')['default']
    First: typeof import('./src/components/First.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GLTFloading: typeof import('./src/components/GLTFloading.vue')['default']
    Particle: typeof import('./src/components/Particle.vue')['default']
    StarrySky: typeof import('./src/components/StarrySky.vue')['default']
  }
}
